name: Tests
run-name: Tests (${{ github.event_name }} ${{ github.event.pull_request.number }})

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  branch_build_tests:
    name: Test build
    uses: ./.github/workflows/build.yml
    with:
      input_version: test
      dbt_target: ci_with_fal
    secrets: inherit
