name: Tests

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  branch_build_tests:
    name: Build test run
    uses: ./.github/workflows/build.yml
    with:
      input: test
    secrets: inherit
