name: Tests
run-name: Tests (github.event_name)

on: [pull_request, workflow_dispatch]
  # pull_request:
  # workflow_dispatch:
  #   inputs:
  #     dbt_schema:
  #       description: DBT schema suffix to use for test build
  #       type: string
  #       required: true
  #       default: workflow_dispatch

env:
  DBT_SCHEMA: fromJSON('[github.event.pull_request.number, workflow_dispatch]')[github.event_name == 'pull_request']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  branch_build_tests:
    name: Test build
    uses: ./.github/workflows/build.yml
    with:
      input_version: test
      dbt_target: ci_with_fal
      dbt_schema: ${{ env.DBT_SCHEMA }}
    secrets: inherit
